### ISSUE TITLE
new Date() sets `this.d` to Invalid Date

### ISSUE THREAD

**Issue by jgreub** [Jimbly/timezone-mock#10]
I think this commit 917d59afc22378ade1bf257489443760e1a851a9  potentially caused a bug.  I'm getting an error anytime calling `getFullYear` when this line is left in, however it works fine when I comment that line.

```javascript
timezoneMock.register('US/Pacific')
new Date().getFullYear()
```

produces this error:
```
Expected value to be (operator: ==):
      true
    Received:
      false

      at MockDate.Object.<anonymous>.MockDate.calcTZO (node_modules/timezone-mock/index.js:60:10)
      at MockDate.(anonymous function) [as getFullYear] (node_modules/timezone-mock/index.js:82:47)
      at Object.<anonymous> (test/project/components/PairingHistoryRecord.spec.js:31:59)
          at new Promise (<anonymous>)
          at <anonymous> thrown
```

It looks like the main change from that commit, `this.fromLocal(new _Date(_Date.UTC.apply(null, arguments)));` always updates `this.d` to an invalid date when simply calling `new Date()`.

Specifically, this `_Date.UTC.apply(null, arguments)` results in an **NaN** when `arguments` is an empty object, which it is when calling `new Date()`

**Potential Solution**:
Maybe add a `if (arguments.length === 0) {` check at the top of the MockDate main function.  I'm not sure if it needs to call `fromLocal` or not. Something like this:

```
if (arguments.length === 0) {
  this.d = new _Date()
} else if (arguments.length ===1) {
  ...
  ...
  ...
```

*Notes*:
It looks like when calling `Date.UTC()`, that two arguments are required (year and month). https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC

**Comment by Jimbly** [comment]
Fixed in #11
