### ISSUE TITLE
Unsupported date format 2019/03/01

### ISSUE THREAD

**Issue by oleg-mtr** [Jimbly/timezone-mock#20]
```
Unhandled date format passed to MockDate constructor: 2019/03/01
```

**Comment by Jimbly** [comment]
That does not appear to be a [valid Date string in Javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Parameters), it is neither a [`IETF-compliant RFC 2822`](https://tools.ietf.org/html/rfc2822#page-14) timestamp nor an [`ISO8601`](http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15) timestamp, and, as far as I can tell, its behavior is undefined by the Javascript spec.  In practice, Node seems to treat it as a local date (as opposed to `2019-03-01`, an ISO8601 date string, that is interpreted as a UTC date).  I'd say you found a potential bug in the program you're writing a test for =).

I could be misreading something, and perhaps that is a valid date string, but I can't find any documentation referencing that.  If you do, let me know, and we could potentially add support to this module for those strings.

It wouldn't be *totally* unreasonable to support these undocumented date formats in this module, but that would require some substantial testing to make sure all browsers/environments treat them exactly the same (e.g. depending on the OS's locale settings, "2019/03/01" may be January 3rd or March 1st).  I took a very quick stab at supporting exactly that date format you listed, in case you really need it, but it doesn't work with other undocumented date formats (e.g. "2019/3/1"), but if you really want it, you can grab it [here](https://github.com/Jimbly/timezone-mock/compare/undocumented_date).
