### ISSUE TITLE
Support mocking _Date with already mocked Date by jasmine

### ISSUE THREAD

**Issue by dongsik-yoo** [Jimbly/timezone-mock#31]
I'm glad to see this library because I'm able to add timezone test cases into my project. 
But I had a small issue about double mocking Date with this library. I use Jasmine and it mocks `Date` first.

```js
import { register, unregister } from 'timezone-mock';

jasmine.clock().install();
jasmine.clock().mockDate(new Date('2020-01-20T00:00:00'));
register(timezoneName);
```

### AS-IS
https://github.com/Jimbly/timezone-mock/blob/e27612065f44e7afe8ec5fa0f5a5a7baef64c402/index.js#L181-L184

### I modified it
So I modified that `global.Date`(already mocked date) assign into `_Date`.

```js
function register(new_timezone, glob = global) {
  timezone = new_timezone || 'US/Pacific';
  _Date = glob.Date; // Modified here
  glob.Date = MockDate;
}
```

### Expected
But it's not sufficient, because there are several codes using `_Date` was assigned at module loading time. 
https://github.com/Jimbly/timezone-mock/blob/e27612065f44e7afe8ec5fa0f5a5a7baef64c402/index.js#L167-L169

Can you support assigning `global.Date` into `_Date`?

**Comment by Jimbly** [comment]
I'd probably accept a pull request with such changes, but don't have the bandwidth to work on that myself at the moment.  You may want consider just using one mock date at a time though - in your tests, register with timezone-mock, do some relevant tests, unregister, then do other tests.

**Comment by Jimbly** [comment]
Actually, even better, if you want timezone-mock to use the mock Date provided by Jasmine, just require timezone-mock *after* installing Jasmine, just like you don't require your own test code until after installing the appropriate mocks.

**Comment by dongsik-yoo** [comment]
It's a good idea to use just require it. Thank you!.

./test/index.ts(jasmine's entry file)
```js
/** Load timezone-mock module properly with jasmine mocking Date. */
function loadTimezoneMock() {
  jasmine.clock().install();
  // eslint-disable-next-line global-require
  require('timezone-mock');
  jasmine.clock().uninstall();
}

loadTimezoneMock();

```
