### ISSUE TITLE
String template literals is not supported on IE

### ISSUE THREAD

**Issue by dongsik-yoo** [Jimbly/timezone-mock#32]
Cross browser test(including IE11) will be failed because of template literals.

https://github.com/Jimbly/timezone-mock/blob/e27612065f44e7afe8ec5fa0f5a5a7baef64c402/index.js#L171-L174

Can you please use string concatenation to support any browser?

**Comment by Jimbly** [comment]
Sorry!  Fixed now and published as v1.0.14.  Let me know if you have any other problems.

**Comment by Jimbly** [comment]
Actually, this might fail on IE due to the default parameter to the `register` function as well.  Slightly less straightforward to fix, but can probably be done.  Note on browsers you probably need to call `timezone_mock.register(timezone, window)` to tell it what global the Date object lives on.

**Comment by dongsik-yoo** [comment]
The default parameter is failed as you said. 
I'm using babel now. But I wish you fix it, too.

**Comment by Jimbly** [comment]
I think I've fixed the issue for accessing `global` in non-Node environments, published to NPM as v1.0.16.  Also added some ESLint rules to catch any future non-old-browser compatible code in the future.

**Comment by dongsik-yoo** [comment]
Thank you so much! This library is very useful.
