### ISSUE TITLE
Australia/Adelaide is missing from TimeZone types

### ISSUE THREAD

**Issue by TwoPlusTwoOne** [Jimbly/timezone-mock#35]
```
export type TimeZone =
  'Brazil/East' |
  'Europe/London' |
  'US/Eastern' 
  'US/Pacific' |
  'UTC';
```

Should be:

```
export type TimeZone =
  'Brazil/East' |
  'Europe/London' |
  'US/Eastern' |
  'US/Pacific' |
  'Australia/Adelaide' |
  'UTC';
```

I tried creating a branch and pushing the fix but it's not open to everyone pushing branches 😄

**Comment by Jimbly** [comment]
Thanks!  On GitHub you usually need to create a branch in your own fork to make a pull request.  If you use the web interface and just click "edit" on the file, it'll do that all automatically for you =).  Trivial fix though, so I just did it.  Published to NPM as v1.0.18.
