### ISSUE TITLE
output of toString() is can be confusing

### ISSUE THREAD

**Issue by timrobinson33** [Jimbly/timezone-mock#37]
calling `new Date().toString()` after using timezone-mock outputs the date like this:
```
Mockday 2020-12-31T20:34:56.000Z GMT-0800 (MockDate)
```
maybe it's just a personal thing but I find it a bit counter-intuitive to show the date in UTC and then put the timezone after it. normally in Javascript, toString() would output the date in local time, when I saw  "GMT-0800" at the end, I assumed it was local time and didn't initially spot the "Z".

**Comment by Jimbly** [comment]
It is a little confusing, though a MockDate is a combination of a UTC date and a TimeZone offset, so it's just showing all of it's internal data.  Other than not being parseable by `new Date()` it doesn't really matter what it shows much, it's primarily for debugging/verification.  Have a suggestion on how to format it instead?

**Comment by timrobinson33** [comment]
personally I would prefer to have it shown as a local time, so for the above example it would be
```
2021-01-01T04:34:56.000-0800
```
which is parseable by `new Date()`. If you want to see it in UTC you can always call toUTCString().

I take your point though that it is just for debugging and verification, and my version doesn't show as much of the internal state

**Comment by Jimbly** [comment]
Up through ES2018, the output of Date.toString() is not guaranteed to be parseable by new Date(), so it's best if it outputs something that will fail to parse, although, admittedly that's not what this module is used for testing, but I'd hate for it to hide a different real bug =).

**Comment by timrobinson33** [comment]
Yes the parse-ability isn't an issue at all. I just find it a bit confusing to show the UTC time with a time zone because normally you would see either UTC or (local + timezone)

**Comment by Jimbly** [comment]
Yep, it is confusing, a mocked date has both ^_^.  How about something like `2020-12-31T20:34:56.000Z UTC (MockDate: GMT-0800)`?

**Comment by timrobinson33** [comment]
Yes I'd certainly be happy with that
