### ISSUE TITLE
thank you for this excellent script :)

### ISSUE THREAD

**Issue by iambumblehead** [Jimbly/timezone-mock#41]
my tests were failing in travis and after adding your script my tests are passing

https://github.com/iambumblehead/simpletime/blob/master/simpletime.spec.js#L9

thank you :)

**Comment by Jimbly** [comment]
You're welcome!

Usually this module is used to *cause* tests to fail, in order to fix bugs that only happen in certain timezones... if it's failing before using this module, maybe you've got a bug?  In theory, any test should pass in at least 2 different timezones (unless you're specifically testing the return of locale-specific date functions... then all's well, carry on... ^_^).

**Comment by iambumblehead** [comment]
@jimbly thnk you _I think_ my tests are working correctly... one of the failing tests before using your package was this one, in which the returned value '05' should be local US/Pacific
```javascript
test("getDateDStr, should return the correct day number", t => {
  //Fri Apr 05 2013 21:23:41 GMT-0700 (PDT)
  var date = new Date(1365222221485);

  t.is(simpletime.getDateDStr(date), '05');
});
```
maybe I'm using time in the wrong way altogether (and feel free to let me know if you think I am), but these functions are working as I intended them to

**Comment by Jimbly** [comment]
If that's expected to be getting the day string in the local timezone, for purely visual display purposes, then that's working just fine.  If it's used for any other purpose (data serialization, logging, communication with other systems, etc), you probably want to use `Date::getUTCDay()` not `Date::getDay()` so the behavior doesn't change based on what timezone of the computer the program is running on.  I have no idea what `simpletime` is, so just generally commenting here, feel free to disregard =).

**Comment by iambumblehead** [comment]
@jimbly thanks I'll update simpletime to use the UTC-naming you recommend here
