### ISSUE TITLE
Not compatible with Luxon fromJSDate within Angular/Jest test?

### ISSUE THREAD

**Issue by stephengeorgewest-navitaire** [Jimbly/timezone-mock#48]
I don't know if this is fixable? or just a something to note.

Luxon fromJSDate checks if the incoming object is a valid date using
`Object.prototype.toString.call(o)`
which returns 
`'[object Object]'`
instead of the expected 
`"[object Date]"`
![image](https://user-images.githubusercontent.com/25107583/127914812-904628ab-ca2e-4aa1-8fb0-08bf5ca301f4.png)

It looks like this should be handled by :
https://github.com/Jimbly/timezone-mock/blob/63afc5fa03cd586441f21090612c68e7988781b3/index.js#L180

But it may be an angular/jest thing, since it is going through zone.js first:
https://github.com/angular/zone.js/blob/b11bd466c20dc338b6d4d5bc3e59868ff263778d/lib/common/to-string.ts#L55
![image](https://user-images.githubusercontent.com/25107583/127917784-3f3fb3d9-3e51-43f8-abf2-bd53f98a4748.png)

![image](https://user-images.githubusercontent.com/25107583/127917897-4a96e174-ce58-465b-ab54-0fa36238b828.png)
which calls 
`Object.prototype.toString.call(this)`, this being mockdate, and I never step into `MockDate.prototype.toString`. Though, I do step into the `function MockDate(param) {` constructor when initializing the date.

My use case was like (a bit is cut off at the end to make the UTC date a local date, but this is where the call stack is at):
![image](https://user-images.githubusercontent.com/25107583/127919230-cc68384d-3b41-4d7e-aef5-d533e906a76c.png)

Called from tests like:
![image](https://user-images.githubusercontent.com/25107583/127919257-46c00a14-0d3e-44e0-b61e-2040186a9680.png)

**Comment by Jimbly** [comment]
> It looks like this should be handled by :
> https://github.com/Jimbly/timezone-mock/blob/63afc5fa03cd586441f21090612c68e7988781b3/index.js#L180

That code handles effectively calling `MockDate.prototype.toString(obj)` where `obj` is a (non-mocked) `Date`, but the mentioned problem is the opposite - calling a native `toString` on a `MockDate`.

I'm not sure if there's a better way, but that code you quoted looks like almost exactly what would be required to fix this!  E.g. inside of `register()`, we need to similarly patch `Object.prototype.toString` to return `[object Date]` if `this instanceof MockDate`.  Seems super simple, so I went ahead and did it, can you please test the version just pushed to `master` here and see if it resolves your problem?  If so, I'll publish it to NPM.

**Comment by stephengeorgewest-navitaire** [comment]
Hot dog, that was fast. That looks like it fixes it.

**Comment by Jimbly** [comment]
Heh, I started typing a message saying a PR would be welcome, and explaining what a good test to add before fixing it, but realized it'd take the same amount of time to just fix it, if the code you linked to worked for that other project ;).

Anyway, published to NPM as v1.2.0 now
