### ISSUE TITLE
Error loading module ast-types after updating timezone-mock from 1.1.4 to 1.2.0

### ISSUE THREAD

**Issue by janamtote** [Jimbly/timezone-mock#49]
Hello! First, thank you for creating this library!

We updated the timezone-mock in our projects and we're currently getting the following error:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.from (/tsg/.yarn/cache/ast-types-npm-0.14.2-43c4ac4b0d-8674a77307.zip/node_modules/ast-types/lib/types.js:260:46)
    at /tsg/.yarn/cache/ast-types-npm-0.14.2-43c4ac4b0d-8674a77307.zip/node_modules/ast-types/lib/types.js:236:71
    at Array.map (<anonymous>)
    at or (/tsg/.yarn/cache/ast-types-npm-0.14.2-43c4ac4b0d-8674a77307.zip/node_modules/ast-types/lib/types.js:236:37)
    at default_1 (/tsg/.yarn/cache/ast-types-npm-0.14.2-43c4ac4b0d-8674a77307.zip/node_modules/ast-types/def/core.js:18:23)
    at use (/tsg/.yarn/cache/ast-types-npm-0.14.2-43c4ac4b0d-8674a77307.zip/node_modules/ast-types/fork.js:45:31)
    at Array.forEach (<anonymous>)
    at Object.default_1 [as default] (/tsg/.yarn/cache/ast-types-npm-0.14.2-43c4ac4b0d-8674a77307.zip/node_modules/ast-types/fork.js:12:10)
    at Object.<anonymous> (/tsg/.yarn/cache/ast-types-npm-0.14.2-43c4ac4b0d-8674a77307.zip/node_modules/ast-types/main.js:21:24)
```

I can't find any direct relation between `timezone-mock` and `ast-types` but I'm 100% sure that the only variable is the change from timezone-mock v1.1.4 to 1.2.0.. I don't see anything in the [changes in the actual source code of timezone-mock](https://github.com/Jimbly/timezone-mock/commit/1e0c410916764143cb32b1f5078e3b83f3257f3d) that would cause the issue but I might be missing something obvious for JS developers (I mostly develop in C# :) )

Thank you!

**Comment by Jimbly** [comment]
Hi!

Hmm, not sure what would cause that, but if you're sure it's from bumping timezone-mock, try manually commenting out the line `Object.prototype.toString = mockDateObjectToString;` in `node_modules/timezone-mock/index.js` and let me know if the problem goes away, as that seems the most suspicious, though the code was copied from some other mocking library so I assumed it was safe-ish, and I can't actually see any way it would be causing that error...

**Comment by janamtote** [comment]
commenting `Object.prototype.toString = mockDateObjectToString;` fixed the issue

**Comment by janamtote** [comment]
Moving the `.call(this)` to the `register` function also works.. Though not sure what that really does.

```js
var orig_object_toString;
function mockDateObjectToString() {
  ...
  return orig_object_toString;
}

function register(new_timezone, glob) {
   ...
    Object.prototype.toString = mockDateObjectToString.call(this);
}
```

**Comment by janamtote** [comment]
both still throws an error

**Comment by Jimbly** [comment]
Okay, did some testing, I *think* understand what's going on, and it's weird black magic ;).  Try adding this line to the very top of `index.js`, and otherwise everything back how it was =):
```javascript
"use strict";
```
Apparently Function.protoype.call has some _weird_ behavior if not in "strict mode", so that's probably it =).

**Comment by Jimbly** [comment]
Actually, I'm pretty convinced that's the issue, just try `timezone-mock@1.2.1` =).

**Comment by janamtote** [comment]
Updating to 1.2.1 works like a charm! Thank you for resolving this issue so fast! Closing as fixed
