### ISSUE TITLE
Add `America/Sao_Paulo` (replaces `Brazil/East`) time zone

### ISSUE THREAD

**Issue by micalevisk** [Jimbly/timezone-mock#52]
![image](https://user-images.githubusercontent.com/13461315/139937218-e6f1b64e-f8ea-498e-b2c2-770876a818a9.png)

I think you can keep both to avoid breaking changes, idk

---

https://github.com/Jimbly/timezone-mock/blob/01ce892d68f79a4d479db1a312d461cf664082b8/lib/tzdata.js#L432

https://github.com/Jimbly/timezone-mock/blob/01ce892d68f79a4d479db1a312d461cf664082b8/index.d.ts#L11

https://github.com/Jimbly/timezone-mock/blob/735c20b7b91548d7170772d31b4dc5e2bb534e7b/README.md#L62

https://github.com/Jimbly/timezone-mock/blob/a59bc09584151ba2a747eff6cf544e0e914d736e/tests/test-constructors.js#L97-L102

**Comment by Jimbly** [comment]
According to that website (looks like probably timezoneconverter.com), `US/Pacific` and `US/East` are also "obsolete", but, especially for writing tests, I find those names *much* more meaningful and readable than relatively arbitrary city names.  This module intentionally only supports mocking a few problematic and representative time zones listed in the README, not all time zones, so I think it's fine to leave them as their friendly, non-technical names.

**Comment by micalevisk** [comment]
Got it! thanks
