### ISSUE TITLE
Date constructor arguments evaluated as UTC 

### ISSUE THREAD

**Issue by emil2k** [Jimbly/timezone-mock#59]
The constructor arguments are handled as if they are in UTC instead of the local timezone here:
https://github.com/Jimbly/timezone-mock/blob/master/index.js#L54

This seems to deviate from the standard implementation: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

> Individual date and time component values Given at least a year and month, this form of Date() returns a Date object whose component values (year, month, day, hour, minute, second, and millisecond) all come from the following parameters. Any missing fields are given the lowest possible value (1 for day and 0 for every other component). **The parameter values are all evaluated against the local time zone, rather than UTC.**

Let me know and I can put up a PR to fix this.

**Comment by Jimbly** [comment]
The line referenced appears to be calling `fromLocal()`, which should be interpreting them in the mocked (local) time zone already.  Have a particular case that's doing the wrong thing?

**Comment by emil2k** [comment]
@Jimbly With the `Australia/Adelaide` timezone registered, I'm calling `new Date(2022, 5, 1)` which should produce a June 1st date, but outputs May 31st at 14:30.

**Comment by Jimbly** [comment]
That is the right (UTC) time for such a date, I think?  Looks right to me:
```javascript
> require('timezone-mock').register('Australia/Adelaide')
undefined
> new Date(2022,5,1).toLocaleString()
'6/1/2022, 12:00:00 AM'
> new Date(2022,5,1).toUTCString()
'Tue, 31 May 2022 14:30:00 GMT'
```

**Comment by emil2k** [comment]
You are right, looking at it a bit closer it seems the issue has something to do with how the formatter is using the mocked instance - it processes as if it is in UTC instead of the local timezone.

My snippet looks like this:

```
    timezone_mock.register('Australia/Adelaide');
    const dateFormatter = new Intl.DateTimeFormat('en-US');
    console.log("INPUT:", date);
    console.log(
        'DATE ARGS:',
        date.getUTCFullYear(),
        date.getUTCMonth(),
        date.getUTCDate()
    );
    const out = new Date(
        date.getUTCFullYear(),
        date.getUTCMonth(),
        date.getUTCDate()
    );
    console.log('OUTPUT:', out, out.toLocaleString(), out.toUTCString());
    console.log('FORMATTED:', dateFormatter.format(out))
```

Which produces this output:

```
    INPUT: MockDate { d: 2022-06-01T00:00:00.000Z }
    DATE ARGS: 2022 5 1
    OUTPUT: MockDate { d: 2022-05-31T14:30:00.000Z } 6/1/2022, 12:00:00 AM Tue, 31 May 2022 14:30:00 GMT
    FORMATTED: 5/31/2022
```

I would expect the formatted output to be `6/1/2022`.

**Comment by Jimbly** [comment]
I'm not familiar with `Intl.DateTimeFormat`, I think it post-dates this library by a bit =).  It must be accessing something internal on the MockDate without going through .getUTCFullYear/etc or .getTime or any of the other mocked interfaces (or, some interface that's mocked but not returning the right thing), if you can figure out what exactly (either by setting breakpoints / logging or perhaps it's defined in the spec...) we could probably mock that.

**Comment by Jimbly** [comment]
Hmm, or, maybe it's actually doing the "right" thing - nothing is mocking `Intl.DateTimeFormat`, so it's formatting this Date object into your local time itself, I'm assuming in your local time, with no mocking, that ` new Intl.DateTimeFormat('en-us').format(new Date('2022-05-31T14:30:00Z'))` is `5/31/2022`?  Might not be able to fix this without mocking Intl.DateTimeFormat.

**Comment by emil2k** [comment]
Yeah, I ended up mocking `Intl.DateTimeFormat` also. Sorry, for the false alarm - we can probably close this.
