### ISSUE TITLE
With the latest 1.3.3 version I am getting Date is not a constructor

### ISSUE THREAD

**Issue by richtera** [Jimbly/timezone-mock#61]
Tracing through the code it seems the global Date is null unless the mock is activated. The tests with the activated date mock seem to pass but the ones that just include the module but don't need different timezones seem to fail.

**Comment by Jimbly** [comment]
Hi, thanks for reporting.

I'm not able to reproduce this, though some stuff changed with how the global is modified, it sounds related to that change, nothing pops out as me as to the cause.  Do you have an example?  I tried this, and it works fine:
```
var timezone_mock = require('timezone-mock');

new Date();
```

**Comment by Jimbly** [comment]
Ah, any chance you have a test that is calling `unregister()` without ever first calling `register()`?  That looks like it might cause this (and I'll fix it here, but would be good to confirm that's the cause).

**Comment by Jimbly** [comment]
Okay, should be fixed in `1.3.4`.  Please give it a try and let me know =)

**Comment by richtera** [comment]
Works, thank you!
