### ISSUE TITLE
GMT Offsets appear to work in opposite direction

### ISSUE THREAD

**Issue by taylorkline** [Jimbly/timezone-mock#62]
Great apologies, but I don't have time to create a reproducible example, but as a quick summary:

```tsx
tzMock.register("US/Eastern");
format(new Date("2022-08-17"), "yyyy-MM-dd HH:mm:ssXXX");
// => "2022-08-16 20:00:00-04:00"

// on the other hand
tzMock.register("Etc/GMT-4");
format(new Date("2022-08-17"), "yyyy-MM-dd HH:mm:ssXXX");
// => "2022-08-17 04:00:00+04:00"
```

**Comment by Jimbly** [comment]
What's `format`?  Assuming it's another library, depending on what it's doing, you may need to register the mock'd date object before requiring it, or possibly something else is going wrong...

**Comment by taylorkline** [comment]
It's from date-fns and used like:

`import { format } from "date-fns";`

**Comment by billop** [comment]
I can reproduce this issue

https://codesandbox.io/s/cold-water-lo0c8m?file=/src/index.js

**Comment by Jimbly** [comment]
If it's just a data issue, not a formatting issue, perhaps the data added in #57 by @jacobwahoo wasn't right (flipped sign)?

**Comment by jacobwahoo** [comment]
I know it's weird, but for the Etc/GMT offsets, the convention is to reverse the direction. Don't ask my why.

Here's a list on IBM's website. You can see that Etc/GMT+12 is equivalent to GMT-12:00

https://www.ibm.com/docs/en/cloudpakw3700/2.3.0.0?topic=SS6PD2_2.3.0/doc/psapsys_restapi/time_zone_list.html

Here's a post on the Oracle community about how confusing it is:
https://community.oracle.com/tech/developers/discussion/3563188/etc-gmt-time-zones-confusing

So the time zones are fine. It's the convention that's messed up.

**Comment by taylorkline** [comment]
Thank you @jacobwahoo .

Given that amazing answer I believe my issue here can be safely closed, unless anyone disagrees.

**Comment by jacobwahoo** [comment]
It might be worth updating the README to say that they are backwards from what you might expect. Maybe we can avoid this confusion in the future

**Comment by Jimbly** [comment]
Wow, that is confusing!  Are there better numerically-named timezones to use instead of Etc/GMT+ that should be used here?  If not, just a note in the README.md is probably a good idea =).

**Comment by jacobwahoo** [comment]
@Jimbly Not that I saw, but my comment above has an enumeration of the timezone folder from my Ubuntu WSL instance if you want to look for yourself.

**Comment by Jimbly** [comment]
Okay, thanks for checking.  I've added a note to the README and will consider this closed =).
